// Mock events data
const eventsData = [
    {
        id: 1,
        title: "Varsity Football Game",
        description: "Come support our Eagles as they take on the rival Lions...",
        date: "2025-05-10",
        time: "19:00",
        location: "School Stadium",
        category: "Sports",
        image: "https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2024%2F1020%2Fr1403332_1296x729_16%2D9.jpg",
        organizer: "Athletics Department",
        contact: "athletics@school.edu"
    },
    {
        id: 2,
        title: "Spring Art Exhibition",
        description: "Annual showcase of student artwork...",
        date: "2025-05-15",
        time: "17:00",
        location: "School Gallery",
        category: "Arts",
        image: "https://placehold.co/600x400?text=Spring+Art+Exhibition",
        organizer: "Art Department",
        contact: "art@school.edu"
    },
    {
        id: 3,
        title: "Science Fair",
        description: "Students present their scientific research projects...",
        date: "2025-05-18",
        time: "10:00",
        location: "School Gymnasium",
        category: "Academics",
        image: "https://placehold.co/600x400?text=Science+Fair",
        organizer: "Science Department",
        contact: "science@school.edu"
    },
    {
        id: 4,
        title: "Debate Club Tournament",
        description: "Our award-winning debate team hosts schools...",
        date: "2025-05-20",
        time: "09:00",
        location: "Auditorium",
        category: "Clubs",
        image: "https://placehold.co/600x400?text=Debate+Club+Tournament",
        organizer: "Debate Club",
        contact: "debate@school.edu"
    },
    {
        id: 5,
        title: "Robotics Workshop",
        description: "Learn the basics of robotics and programming...",
        date: "2025-05-22",
        time: "15:30",
        location: "Technology Lab",
        category: "Academics",
        image: "https://placehold.co/600x400?text=Robotics+Workshop",
        organizer: "Technology Club",
        contact: "tech@school.edu"
    },
    {
        id: 6,
        title: "Spring Concert",
        description: "Join us for an evening of music...",
        date: "2025-05-25",
        time: "19:00",
        location: "Auditorium",
        category: "Music",
        image: "https://placehold.co/600x400?text=Spring+Concert",
        organizer: "Music Department",
        contact: "music@school.edu"
    },
    {
        id: 7,
        title: "Basketball Tryouts",
        description: "Tryouts for next year's basketball teams...",
        date: "2025-05-27",
        time: "16:00",
        location: "Gymnasium",
        category: "Sports",
        image: "https://placehold.co/600x400?text=Basketball+Tryouts",
        organizer: "Athletics Department",
        contact: "athletics@school.edu"
    },
    {
        id: 8,
        title: "Student Council Elections",
        description: "Cast your vote for next year's student council...",
        date: "2025-05-28",
        time: "12:00",
        location: "Main Hall",
        category: "Clubs",
        image: "https://placehold.co/600x400?text=Student+Council+Elections",
        organizer: "Student Council",
        contact: "studentcouncil@school.edu"
    },
    {
        id: 9,
        title: "Environmental Club Beach Cleanup",
        description: "Join the Environmental Club for our monthly beach cleanup...",
        date: "2025-05-31",
        time: "09:00",
        location: "City Beach",
        category: "Clubs",
        image: "https://placehold.co/600x400?text=Environmental+Club+Beach+Cleanup",
        organizer: "Environmental Club",
        contact: "envclub@school.edu"
    },
    {
        id: 10,
        title: "International Food Festival",
        description: "Experience cuisines from around the world...",
        date: "2025-06-01",
        time: "17:00",
        location: "Cafeteria",
        category: "Clubs",
        image: "https://placehold.co/600x400?text=International+Food+Festival",
        organizer: "International Club",
        contact: "international@school.edu"
    },
    {
        id: 11,
        title: "Math Competition",
        description: "Test your mathematical skills...",
        date: "2025-06-03",
        time: "15:00",
        location: "Math Wing",
        category: "Academics",
        image: "https://placehold.co/600x400?text=Math+Competition",
        organizer: "Math Department",
        contact: "math@school.edu"
    },
    {
        id: 12,
        title: "Drama Club: Shakespeare in the Park",
        description: "Our Drama Club presents 'A Midsummer Night's Dream'...",
        date: "2025-06-05",
        time: "20:00",
        location: "School Garden",
        category: "Arts",
        image: "https://placehold.co/600x400?text=Drama+Club:+Shakespeare+in+the+Park",
        organizer: "Drama Club",
        contact: "drama@school.edu"
    },
    {
        id: 13,
        title: "Tennis Tournament",
        description: "Annual intramural tennis tournament...",
        date: "2025-06-07",
        time: "09:00",
        location: "Tennis Courts",
        category: "Sports",
        image: "https://placehold.co/600x400?text=Tennis+Tournament",
        organizer: "Athletics Department",
        contact: "athletics@school.edu"
    },
    {
        id: 14,
        title: "Coding Competition",
        description: "Put your programming skills to the test...",
        date: "2025-06-10",
        time: "16:00",
        location: "Computer Lab",
        category: "Academics",
        image: "https://placehold.co/600x400?text=Coding+Competition",
        organizer: "Computer Science Club",
        contact: "compsci@school.edu"
    },
    {
        id: 15,
        title: "Senior Prom",
        description: "This year's theme is 'Starry Night'...",
        date: "2025-06-12",
        time: "19:00",
        location: "Grand Hotel Ballroom",
        category: "Social",
        image: "https://placehold.co/600x400?text=Senior+Prom",
        organizer: "Senior Class Committee",
        contact: "seniors@school.edu"
    },
    {
        id: 16,
        title: "Career Fair",
        description: "Explore future career paths and educational opportunities...",
        date: "2025-06-15",
        time: "10:00",
        location: "Gymnasium",
        category: "Academics",
        image: "https://placehold.co/600x400?text=Career+Fair",
        organizer: "Guidance Department",
        contact: "careers@school.edu"
    },
    {
        id: 17,
        title: "Chess Tournament",
        description: "Test your strategic skills...",
        date: "2025-06-18",
        time: "14:00",
        location: "Library",
        category: "Clubs",
        image: "https://placehold.co/600x400?text=Chess+Tournament",
        organizer: "Chess Club",
        contact: "chess@school.edu"
    },
    {
        id: 18,
        title: "Graduation Ceremony",
        description: "Celebrate the achievements of our graduating seniors...",
        date: "2025-06-20",
        time: "10:00",
        location: "Football Field",
        category: "Social",
        image: "https://placehold.co/600x400?text=Graduation+Ceremony",
        organizer: "Administration",
        contact: "principal@school.edu"
    },
    {
        id: 19,
        title: "Photography Club Exhibition",
        description: "View stunning photographs captured by members...",
        date: "2025-06-25",
        time: "16:00",
        location: "Art Gallery",
        category: "Arts",
        image: "https://placehold.co/600x400?text=Photography+Club+Exhibition",
        organizer: "Photography Club",
        contact: "photo@school.edu"
    },
    {
        id: 20,
        title: "Summer Band Camp",
        description: "One-week intensive music program for band members...",
        date: "2025-07-01",
        time: "09:00",
        location: "Music Building",
        category: "Music",
        image: "https://placehold.co/600x400?text=Summer+Band+Camp",
        organizer: "Music Department",
        contact: "music@school.edu"
    }
  ];
  