// Mock events data
const eventsData = [
    {
      id: 1,
      title: "Bosco Quiz Bowl 2025",
      description: "An inter-house quiz competition testing students' knowledge across various subjects.",
      date: "2025-07-15",
      time: "10:00",
      location: "School Auditorium",
      category: "Academics",
      image: "/assets/boscoquizbowl2025.jpg",
      organizer: "Ms. Ananya Sen (Academic Coordinator)",
      contact: "ananya.sen@dbpc.org"
    },
    {
      id: 2,
      title: "Science Exhibition: Innovate 2025",
      description: "Students showcase innovative science projects and experiments.",
      date: "2025-08-20",
      time: "09:00",
      location: "Science Block, Don Bosco Park Circus",
      category: "Academics",
      image: "/assets/scienceexhibition.jpg",
      organizer: "Mr. Rajiv Mehta (Head of Science Department)",
      contact: "rajiv.mehta@dbpc.org"
    },
    {
      id: 3,
      title: "Math Olympiad Challenge",
      description: "A competitive platform for students to solve complex mathematical problems.",
      date: "2025-09-10",
      time: "10:00",
      location: "Room 101, Academic Block",
      category: "Academics",
      image: "/assets/matholympiad.jpg",
      organizer: "Ms. Priya Sharma (Math Department)",
      contact: "priya.sharma@dbpc.org"
    },
    {
      id: 4,
      title: "Literary Fest: Wordsmiths Unite",
      description: "A celebration of literature with poetry recitations, debates, and storytelling.",
      date: "2025-10-05",
      time: "11:00",
      location: "Library Hall",
      category: "Academics",
      image: "/assets/literaryfest.jpg",
      organizer: "Mr. Arindam Das (English Department)",
      contact: "arindam.das@dbpc.org"
    },
    {
      id: 5,
      title: "Annual Sports Day 2025",
      description: "A day filled with track and field events promoting sportsmanship.",
      date: "2025-11-25",
      time: "08:00",
      location: "School Sports Ground",
      category: "Sports",
      image: "/assets/sportsday.jpg",
      organizer: "Mr. Suresh Kumar (Physical Education Head)",
      contact: "suresh.kumar@dbpc.org"
    },
    {
      id: 6,
      title: "Inter-House Football Tournament",
      description: "Competitive football matches between school houses.",
      date: "2025-12-10",
      time: "15:00",
      location: "Football Field",
      category: "Sports",
      image: "/assets/interhousefootball.jpg",
      organizer: "Coach Rahul Singh",
      contact: "rahul.singh@dbpc.org"
    },
    {
      id: 7,
      title: "Basketball Championship League",
      description: "A knockout basketball tournament fostering team spirit.",
      date: "2026-01-20",
      time: "14:00",
      location: "Basketball Court",
      category: "Sports",
      image: "/assets/basketballtourney.jpg",
      organizer: "Ms. Neha Verma (Sports Coordinator)",
      contact: "neha.verma@dbpc.org"
    },
    {
      id: 8,
      title: "Table Tennis Open",
      description: "An open table tennis tournament for students across all grades.",
      date: "2026-02-15",
      time: "10:00",
      location: "Indoor Sports Hall",
      category: "Sports",
      image: "/assets/tabletennisopen.jpg",
      organizer: "Mr. Amit Roy (Sports Department)",
      contact: "amit.roy@dbpc.org"
    },
    {
      id: 9,
      title: "Bosco Music Fiesta",
      description: "A musical evening featuring performances by the school choir and bands.",
      date: "2026-03-10",
      time: "17:00",
      location: "School Auditorium",
      category: "Music",
      image: "/assets/musicfiesta.jpg",
      organizer: "Mr. Anil D'Souza (Music Teacher)",
      contact: "anil.dsouza@dbpc.org"
    },
    {
      id: 10,
      title: "Inter-School Band Competition",
      description: "Bands from various schools compete showcasing their musical talents.",
      date: "2026-04-05",
      time: "16:00",
      location: "Open Air Stage",
      category: "Music",
      image: "/assets/interschoolband.jpg",
      organizer: "Ms. Rina Mukherjee (Cultural Coordinator)",
      contact: "rina.mukherjee@dbpc.org"
    },
    {
      id: 11,
      title: "Classical Music Workshop",
      description: "A workshop introducing students to Indian classical music.",
      date: "2026-05-15",
      time: "10:00",
      location: "Music Room",
      category: "Music",
      image: "/assets/classicalmusicworkshop.jpg",
      organizer: "Mr. Subhash Chatterjee (Music Department)",
      contact: "subhash.chatterjee@dbpc.org"
    },
    {
      id: 12,
      title: "Choir Competition: Voices of Bosco",
      description: "Inter-house choir competition celebrating vocal harmony.",
      date: "2026-06-20",
      time: "11:00",
      location: "School Auditorium",
      category: "Music",
      image: "/assets/choircomp.jpg",
      organizer: "Ms. Anita Fernandes (Choir Director)",
      contact: "anita.fernandes@dbpc.org"
    },
    {
      id: 13,
      title: "Art Exhibition: Canvas Dreams",
      description: "Display of students' artwork including paintings and sculptures.",
      date: "2026-07-30",
      time: "09:00",
      location: "Art Gallery",
      category: "Arts",
      image: "/assets/artexhibition.jpg",
      organizer: "Mr. Sanjay Kapoor (Art Teacher)",
      contact: "sanjay.kapoor@dbpc.org"
    },
    {
      id: 14,
      title: "Drama Festival: Stagecraft",
      description: "Students perform plays and skits, showcasing their acting skills.",
      date: "2026-08-25",
      time: "17:00",
      location: "School Auditorium",
      category: "Arts",
      image: "/assets/dramafestival.jpg",
      organizer: "Ms. Leena Das (Drama Club Head)",
      contact: "leena.das@dbpc.org"
    },
    {
      id: 15,
      title: "Photography Contest: Through the Lens",
      description: "A competition encouraging students to capture moments through photography.",
      date: "2026-09-15",
      time: "10:00",
      location: "Multimedia Room",
      category: "Arts",
      image: "/assets/photographycontest.jpg",
      organizer: "Mr. Arjun Sen (Photography Club)",
      contact: "arjun.sen@dbpc.org"
    },
    {
      id: 16,
      title: "Craft Workshop: Handmade Wonders",
      description: "Students learn various crafting techniques and create art pieces.",
      date: "2026-10-10",
      time: "09:00",
      location: "Art Room",
      category: "Arts",
      image: "/assets/craftworkshop.jpg",
      organizer: "Ms. Kavita Rao (Art Department)",
      contact: "kavita.rao@dbpc.org"
    },
    {
      id: 17,
      title: "Blood Donation Camp",
      description: "A social initiative encouraging voluntary blood donation.",
      date: "2026-11-20",
      time: "09:00",
      location: "School Infirmary",
      category: "Social",
      image: "/assets/blooddonation.jpg",
      organizer: "Mr. Deepak Sharma (Social Service Club)",
      contact: "deepak.sharma@dbpc.org"
    },
    {
      id: 18,
      title: "Graduation Ceremony",
      description: "Celebrate the achievements of our graduating seniors.",
      date: "2026-12-15",
      time: "10:00",
      location: "School Auditorium",
      category: "Social",
      image: "/assets/gradday.jpg",
      organizer: "Administration",
      contact: "principal@dbpc.org"
    },
    {
      id: 19,
      title: "Environmental Awareness Workshop",
      description: "Learn about environmental conservation and sustainable practices.",
      date: "2027-01-10",
      time: "14:00",
      location: "Science Block",
      category: "Clubs",
      image: "/assets/envaware.jpg",
      organizer: "Environmental Club",
      contact: "eco@dbpc.org"
    },
    {
      id: 20,
      title: "Alumni Reunion 2027",
      description: "Annual gathering of Don Bosco Park Circus alumni to reconnect and celebrate.",
      date: "2027-02-05",
      time: "18:00",
      location: "School Campus",
      category: "Social",
      image: "/assets/reunion.jpg",
      organizer: "Alumni Association",
      contact: "alumni@dbpc.org"
    }
  ];